[package]
name = "advent-of-code"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.93"
clap = { version = "4.5.21", features = ["derive"] }
itertools = "0.13.0"


[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
